# Generated by Django 5.2.4 on 2025-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='language',
            field=models.CharField(default='English', help_text='In which language Author writes', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text='Language of the book', max_length=100),
        ),
    ]
